Susano.StopResource("ox_inventory")
Susano.StopResource("Ox_Inventory")
Susano.StopResource("ox_target")
Susano.StopResource("oxmysql")
--TriggerServerEvent('dx-paycheck:Payout')
--TriggerServerEvent('dx-paycheck:withdrawMoney', count)
--TriggerServerEvent('3dme:shareDisplay', ' uždaro kapotą ')
--TriggerServerEvent('3dme:shareDisplay', ' atidaro kapotą ')
--TriggerServerEvent('3dme:shareDisplay', ' uždaro kapotą ')
--TriggerServerEvent('3dme:shareDisplay', ' atidaro kapotą ')
--TriggerServerEvent('3dme:shareDisplay', ' uždaro duris ')
--TriggerServerEvent('3dme:shareDisplay', ' atidaro duris ')
--TriggerServerEvent('3dme:shareDisplay', ' uždaro duris ')
--TriggerServerEvent('3dme:shareDisplay', ' atidaro duris ')
--TriggerServerEvent('Badger_Discord_API:PlayerLoaded')
--TriggerServerEvent('tackle:tryTackle', GetPlayerServerId(playerid)
--TriggerServerEvent('esx_ambulancejob:onPlayerDistress')
--TriggerServerEvent('cd_dispatch:PlayerLoaded')
--TriggerServerEvent('cd_dispatch:JobSet', GetJob()
--TriggerServerEvent('cd_dispatch:OnDutyChecks', on_duty)
--TriggerServerEvent('cd_dispatch:PlayerLoaded')
--TriggerServerEvent('cd_dispatch:JobSet', GetJob()
--TriggerServerEvent('cd_dispatch:OnDutyChecks', on_duty)
--TriggerServerEvent('cd_dispatch:PlayerLoaded')
--TriggerServerEvent('cd_dispatch:PanicSoundInDistance', GetClosestPlayers(5)
--TriggerServerEvent('cd_dispatch:OnDutyChecks', boolean)
--TriggerServerEvent('cd_dispatch:Debug')
--TriggerServerEvent('cd_easytime:SyncMe', {time = true, weather = true})
--TriggerServerEvent('cd_easytime:SyncMe', {time = true, weather = true})
--TriggerServerEvent('cd_easytime:SyncMe', {time = true, weather = true})
--TriggerServerEvent('cd_easytime:SyncMe')
--TriggerServerEvent('cd_easytime:ToggleInstantChange:Time', data.instanttime)
--TriggerServerEvent('cd_easytime:ToggleInstantChange:Weather', data.instantweather)
--TriggerServerEvent('cd_easytime:ForceUpdate', data.values)
--TriggerServerEvent('cd_easytime:SaveSettings')
--TriggerServerEvent('cd_easytime:SyncMe')
--TriggerServerEvent("tuning:saveVehicleModifications",json.encode(data)
--TriggerServerEvent('daily_rewards:claim')
--TriggerServerEvent('daily_rewards:getHistory')
--TriggerServerEvent('friends:requestHandShake', id)
--TriggerServerEvent('dec4t-gangs:storeJobVehicle', props)
--TriggerServerEvent('d-gangzones:addMember', Current.title)
--TriggerServerEvent('d-gangzones:removeMember', self.info?.title)
--TriggerServerEvent('d-gangzones:takeZone', Zone.title)
--TriggerServerEvent('d-gangzones:takeZone', Zone.title, input[2], input[1])
--TriggerServerEvent('d-gangzones:acceptedFight', ZONE_REQUEST.zoneKey)
--TriggerServerEvent('d-gangzones:canceledFight', ZONE_REQUEST.zoneKey)
--TriggerServerEvent("x99-vehstance:server:sync", GetVehicleNumberPlateText(_vehicle)
--TriggerServerEvent('carkeys:RequestVehicleLock', VehToNet(_vehicle)
--TriggerServerEvent('qb-vehiclekeys:server:setVehLockState', NetworkGetNetworkIdFromEntity(_vehicle)
--TriggerServerEvent('d_imports:setDimension')
--TriggerServerEvent('twox-mechanic:deleteveh', NetworkGetNetworkIdFromEntity(vehicle)
--TriggerServerEvent('esx_billing:isiustiisrasa', SPlayer, 'society_'..Job.name, reason, amount)
--TriggerServerEvent('esx_billing:isiustiisrasa', SPlayer, 'society_'..Job.name, data.reason, data.amount)
--TriggerServerEvent('itemsounds:removeSound', soundId)
--TriggerServerEvent('itemsounds:removeSound', soundId)
--TriggerServerEvent('esx_policejob:setDuty', true)
--TriggerServerEvent('twox-police:changeDuty', true)
--TriggerServerEvent('itemsounds:removeSound', soundId)
--TriggerServerEvent('itemsounds:removeSound', soundId)
--TriggerServerEvent('esx_policejob:setDuty', false)
--TriggerServerEvent('twox-police:changeDuty', false)
--TriggerServerEvent('twox-police:deleteveh', NetworkGetNetworkIdFromEntity(vehicle)
--TriggerServerEvent('twox-police:unlockveh', NetworkGetNetworkIdFromEntity(vehicle)
--TriggerServerEvent('dec4t-signalizacija:removeLockpick')
--TriggerServerEvent('redzone:unlockVehicle')
--TriggerServerEvent('dec4t-signalizacija:removeLockpick')
--TriggerServerEvent('dec4t-signalizacija:unlockVehicle', NetID)
--TriggerServerEvent('dec4t-signalizacija:startEngine', NetID)
--TriggerServerEvent('twox-giveTempKeys', plyId, Plate)
--TriggerServerEvent('twox-giveTempKeys', plyId, NetworkGetNetworkIdFromEntity(vehicle)
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('deivuks-items:putHeadBag', targetServerId)
--TriggerServerEvent('deivuks-items:removeHeadBag', targetServerId)
--TriggerServerEvent("deivuks-items:releaseHostage", hostage.targetServerId)
--TriggerServerEvent("deivuks-items:killHostage", hostage.targetServerId)
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('esx:enteredVehicle', current.plate, current.seat, current.displayName, current.netId)
--TriggerServerEvent('esx:exitedVehicle', current.plate, current.seat, current.displayName, current.netId)
--TriggerServerEvent('esx:playerPedChanged', PedToNet(value)
--TriggerServerEvent('deivuks-test:testuoti', 2)
--TriggerServerEvent('deivuks-test:removeEntities', netObjects)
--TriggerServerEvent('dz-drone:server:DoSyncDrone', ObjToNet(drone)
--TriggerServerEvent('dz-drone:server:RemoveItem', item)
--TriggerServerEvent('dz-drone:server:RemoveItem', item)
--TriggerServerEvent('dz-drone:server:RemoveItem', item)
--TriggerServerEvent('esx_skin:save', skin)
--TriggerServerEvent('esx_barbershop:pay')
--TriggerServerEvent('Boost-Logs:SendLog', logas)
--TriggerServerEvent('Boost-Logs:SendLog', logas)
--TriggerServerEvent('esx_skin:setWeight', skin)
--TriggerServerEvent('esx_skin:save', skin)
--TriggerServerEvent('esx_skin:responseSaveSkin', skin)
--TriggerServerEvent('esx_society:checkSocietyBalance', society)
--TriggerServerEvent('esx_society:withdrawMoney', society, amount)
--TriggerServerEvent('esx_society:depositMoney', society, amount)
--TriggerServerEvent('esx_society:washMoney', society, amount)
--TriggerServerEvent('esx_billing:isiustiisrasa', cache.serverId, 'society_admin', ('Greicio virsijimas (%sKM/H)
--TriggerServerEvent('esx_status:update', GetStatusData(true)
--TriggerServerEvent('esx:giveInventoryItem', selectedPlayerId, itemType, item, nil)
--TriggerServerEvent('esx:giveInventoryItem', selectedPlayerId, itemType, item, quantity)
--TriggerServerEvent('esx:removeInventoryItem', itemType, item)
--TriggerServerEvent('esx:removeInventoryItem', itemType, item, quantity)
--TriggerServerEvent('esx:useItem', item)
--TriggerServerEvent('esx:giveInventoryItem', GetPlayerServerId(closestPlayer)
--TriggerServerEvent('esx:onPlayerJoined')
--TriggerServerEvent('esx:onPlayerSpawn')
--TriggerServerEvent('esx:updateWeaponAmmo', weapon.name, ammoCount)
--TriggerServerEvent('esx:onPickup', pickupId)
--TriggerServerEvent('esx:playerPedChanged', PedToNet(playerPed)
--TriggerServerEvent('esx:playerJumping')
--TriggerServerEvent('esx:enteringVehicle', plate, seat, netId)
--TriggerServerEvent('esx:enteringVehicleAborted')
--TriggerServerEvent('esx:enteredVehicle', current.plate, current.seat, current.displayName, current.netId)
--TriggerServerEvent('esx:exitedVehicle', current.plate, current.seat, current.displayName, current.netId)
--TriggerServerEvent('esx:triggerServerCallback', eventName, RequestId, GetInvokingResource()
--TriggerServerEvent('esx:clientCallback', requestId, invoker, ...)
--TriggerServerEvent('esx:onPlayerDeath', data)
--TriggerServerEvent('esx:onPlayerDeath', data)
--TriggerServerEvent('fingerprint-scanner:scanFinger', serverId)
--TriggerServerEvent('fingerprint-scanner:showData', selfData)
--TriggerServerEvent('instance:create', type, data)
--TriggerServerEvent('instance:close')
--TriggerServerEvent('instance:enter', instance.host)
--TriggerServerEvent('instance:leave', instance.host)
--TriggerServerEvent('instance:invite', instance.host, type, player, data)
--TriggerServerEvent('carwash:DoVehicleWashParticles', VehToNet(vehicle)
--TriggerServerEvent('promocodes:getPromocodes')
--TriggerServerEvent('promocodes:createPromocode', code, rewards)
--TriggerServerEvent('promocodes:deletePromocode', code)
--TriggerServerEvent('promocodes:usePromocode', code)
--TriggerServerEvent('_chat:messageEntered', GetPlayerName(id)
--TriggerServerEvent('mChat:CheckPlayerPermissions')
--TriggerServerEvent('mChat:CheckPlayerPermissions')
--TriggerServerEvent('mChat:CheckPlayerPermissions')
--TriggerServerEvent('mChat:CheckPlayerPermissions')
--TriggerServerEvent('mChat:CheckPlayerPermissions')
--TriggerServerEvent('1X-ID:AddTypingPlayer', false)
--TriggerServerEvent('1X-ID:AddTypingPlayer', true)
--TriggerServerEvent('txsv:logger:deathEvent', killer, deathReason)
--TriggerServerEvent('txsv:req:serverCtx')
--TriggerServerEvent('txsv:ackWarning', actionId)
--TriggerServerEvent('txsv:startedWalking')
--TriggerServerEvent('txsv:req:plist:getDetailed', requirePlayerNames)
--TriggerServerEvent('txsv:req:plist:getDetailed')
--TriggerServerEvent('txsv:checkIfAdmin')
--TriggerServerEvent('txsv:checkIfAdmin')
--TriggerServerEvent('txsv:req:freezePlayer', targetPlayerId)
--TriggerServerEvent('txsv:req:tpToCoords', data.x + 0.0, data.y + 0.0, data.z + 0.0)
--TriggerServerEvent('txsv:req:tpToWaypoint')
--TriggerServerEvent('txsv:req:tpToCoords', lastTpCoords.x, lastTpCoords.y, lastTpCoords.z)
--TriggerServerEvent('txsv:req:tpToPlayer', tonumber(data.id)
--TriggerServerEvent('txsv:req:bringPlayer', tonumber(data.id)
--TriggerServerEvent('txsv:req:clearArea', radius)
--TriggerServerEvent('txsv:req:healPlayer', tonumber(data.id)
--TriggerServerEvent('txsv:req:healMyself')
--TriggerServerEvent('txsv:req:healEveryone')
--TriggerServerEvent('txsv:req:sendAnnouncement', data.message)
--TriggerServerEvent('txsv:req:showPlayerIDs', not isPlayerIdsEnabled)
--TriggerServerEvent('txsv:req:changePlayerMode', mode, nearbyPlayers)
--TriggerServerEvent('txsv:req:changePlayerMode', 'none', nearbyPlayers)
--TriggerServerEvent('txsv:req:spectate:end')
--TriggerServerEvent('txsv:req:spectate:cycle', storedTargetServerId, isNext)
--TriggerServerEvent('txsv:req:spectate:start', tonumber(data.id)
--TriggerServerEvent('txsv:req:troll:setDrunk', tonumber(data.id)
--TriggerServerEvent('txsv:req:troll:setOnFire', tonumber(data.id)
--TriggerServerEvent('txsv:req:troll:wildAttack', tonumber(data.id)
--TriggerServerEvent('txsv:req:vehicle:spawn:fivem', model, modelType)
--TriggerServerEvent('txsv:req:vehicle:spawn:redm', model)
--TriggerServerEvent("txsv:req:vehicle:delete", vehNetId)
--TriggerServerEvent('txsv:req:vehicle:fix')
--TriggerServerEvent('txsv:req:vehicle:boost')
--TriggerServerEvent('txsv:webpipe:req', id, method, path, headers, body or '')
--TriggerServerEvent('okokContract:SendVehicleInfo', data.vehicle_description, data.vehicle_price)
--TriggerServerEvent('okokContract:SendContractToBuyer', data)
--TriggerServerEvent('okokContract:changeVehicleOwner', data)
--TriggerServerEvent('onex-dokumentai:show-player', GetPlayerServerId(closestPlayer)
--TriggerServerEvent('gunroulette:requestPlay', tableId, input[2], input[1])
--TriggerServerEvent("gunroulette:startGame", tableId)
--TriggerServerEvent("gunroulette:rejectInvitation", tableId)
--TriggerServerEvent("gunroulette:endGame", tableId)
--TriggerServerEvent('oxmysql:fetchResource', data)
--TriggerServerEvent('ox_doorlock:setState', ClosestDoor.id, newState)
--TriggerServerEvent('ox_doorlock:setState', ClosestDoor.id, newState)
--TriggerServerEvent('ox_doorlock:setState', door.id, door.state == 1 and 0 or 1, true)
--TriggerServerEvent('ox_doorlock:breakLockpick')
--TriggerServerEvent('ox_doorlock:editDoorlock', data.id or false, data)
--TriggerServerEvent('ox_doorlock:editDoorlock', id)
--TriggerServerEvent('ox_inventory:usedItemInternal', slot)
--TriggerServerEvent('ox_inventory:closeInventory')
--TriggerServerEvent('ox_inventory:updateWeapon', 'ammo', weaponAmmo)
--TriggerServerEvent('ox_inventory:updateWeapon', 'melee', currentWeapon.melee)
--TriggerServerEvent('ox_inventory:updateWeapon', 'throw', nil, weapon.slot)
--TriggerServerEvent('ox_inventory:updateWeapon', 'component', data)
--TriggerServerEvent('ox_target:setEntityHasOptions', netId)
--TriggerServerEvent('ox_target:toggleEntityDoor', VehToNet(entity)
--TriggerServerEvent(option.serverEvent, getResponse(option, true)
--TriggerServerEvent('reload_death:setDead', dead)
--TriggerServerEvent('esx:onPlayerSpawn')
--TriggerServerEvent('esx:updateLastPosition', formattedCoords)
--TriggerServerEvent('reload_death:setDead', false)
--TriggerServerEvent('esx:updateLastPosition', formattedCoords)
--TriggerServerEvent('reload_death:setDead', false)
--TriggerServerEvent('esx_kariuomene:setDuty', true)
--TriggerServerEvent('simas-kariuomene:changeDuty', true)
--TriggerServerEvent('esx_kariuomene:setDuty', false)
--TriggerServerEvent('simas-kariuomene:changeDuty', false)
--TriggerServerEvent('simas-kariuomene:deleteveh', NetworkGetNetworkIdFromEntity(vehicle)
--TriggerServerEvent('simas-kariuomene:unlockveh', NetworkGetNetworkIdFromEntity(vehicle)
--TriggerServerEvent('k-jail:server:removeJailItems')
--TriggerServerEvent('k-jail:server:jailPlayer', target, minutes, reason)
--TriggerServerEvent("TunningSystem:Used", nomidaberto)
--TriggerServerEvent("TunningSystem:Used", nomidaberto)
--TriggerServerEvent("TunningSystem:PayModifications",preco,nomidaberto,ESX.Game.GetVehicleProperties(carroselected)
--TriggerServerEvent("TunningSystem:Used", nomidaberto)
--TriggerServerEvent("TunningSystem:Used", nomidaberto)
--TriggerServerEvent('fancy_shop:buyItems',_d.cart,_d.total,_d.paymentType)
--TriggerServerEvent('fancy_shop:robbery:notifyPolice',_i)
--TriggerServerEvent('fancy_shop:robbery:cashierComplete',_i,_tk)
--TriggerServerEvent('fancy_shop:robbery:cancel',_i)
--TriggerServerEvent('fancy_shop:robbery:registerComplete',_i,_tk)
--TriggerServerEvent('fancy_shop:robbery:cancel',_i)
--TriggerServerEvent('fancy_shop:robbery:cancel',_i)
--TriggerServerEvent('fancy_shop:robbery:notifyPolice',_i)
--TriggerServerEvent('fancy_shop:robbery:safeComplete',_i,_tk)
--TriggerServerEvent('fancy_shop:robbery:cancel',_i)
--TriggerServerEvent('fancy_shop:robbery:cancel',_i)
--TriggerServerEvent("vms_clothestore:acceptOutfit", requesterId, outfitName, outfitTable)
--TriggerServerEvent('vSync:requestSync')
--TriggerServerEvent('vms_multichars:relog')
--TriggerServerEvent("0R-gps:Server:SendPanicNotification", gPlayer.channelId, message)
--TriggerServerEvent("0R-gps:Server:RemovePanicNotification", panicId)
--TriggerServerEvent("0R-gps:Server:DisconnectFromChannel", gPlayer.channelId)
--TriggerServerEvent("0R-gps:Server:RemoveGpsFromVehicle", plate)
--TriggerServerEvent("0R-gps:Server:DetachGpsToTarget", PlayerData.identifier)
--TriggerServerEvent("0R-gps:Server:ConnectToChannel", channelId, callSign)
--TriggerServerEvent("0R-gps:Server:AttachGpsToVehicle", vehiclePlate, networkId)
--TriggerServerEvent("0R-gps:Server:DetachGpsToVehicle", plate)
--TriggerServerEvent("0R-gps:Server:DetachGpsToVehicle", plate)
--TriggerServerEvent("0R-gps:Server:AttachGpsToTarget", TargetServerId)
--TriggerServerEvent("0R-gps:Server:DetachGpsToVehicle", plate, true)
--TriggerServerEvent("0R-gps:Server:DetachGpsToTarget", targetIdentifier, true)
--TriggerServerEvent("0R-gps:Server:ShockToTarget", targetIdentifier)
--TriggerServerEvent("vehicles_keys:selfGiveVehicleKeys", plate)
--TriggerServerEvent('qb-clothes:loadPlayerSkin')
--TriggerServerEvent("17mov_Hud:RequestSocietyMoney")
--TriggerServerEvent('hud:server:GainStress', 1)
--TriggerServerEvent('hud:server:GainStress', 1)
--TriggerServerEvent("17mov_Hud:RequestSocietyMoney")
--TriggerServerEvent("vehicles_keys:selfGiveVehicleKeys", plate)
--TriggerServerEvent('qb-clothes:loadPlayerSkin')
--TriggerServerEvent("vehicles_keys:selfGiveVehicleKeys", plate)
--TriggerServerEvent('qb-clothes:loadPlayerSkin')
--TriggerServerEvent("vehicles_keys:selfGiveVehicleKeys", plate)
--TriggerServerEvent('qb-clothes:loadPlayerSkin')
--TriggerServerEvent(event, eventName, id, ...)
--TriggerServerEvent("17mov_divers:CollectTreasure_")
--TriggerServerEvent("17mov_divers:ClientReactRequest", accepted)
--TriggerServerEvent("17mov_divers:KickPlayerFromLobby", targetId, true)
--TriggerServerEvent("17mov_divers:StartJob_sv")
--TriggerServerEvent("17mov_divers:UploadVehicleNetId", JobVehicleNetId)
--TriggerServerEvent("17mov_divers:endJob_sv", true)
--TriggerServerEvent("17mov_divers:endJob_sv", false)
--TriggerServerEvent("vehicles_keys:selfGiveVehicleKeys", plate)
--TriggerServerEvent('qb-clothes:loadPlayerSkin')
--TriggerServerEvent('qs-smartphone:server:sendJobAlert', {message = msg, location = GetEntityCoords(PlayerPedId()
--TriggerServerEvent('gksphone:jbmessage', name, Races[1].phone_number, msg, '', GPS, "ambulance")
--TriggerServerEvent('ars_ambulancejob:updateDeathStatus', deathStatus)
--TriggerServerEvent("ars_ambulancejob:removeInventory")
--TriggerServerEvent('ars_ambulancejob:updateDeathStatus', deathData)
--TriggerServerEvent("ars_ambulancejob:healPlayer", dataToSend)
--TriggerServerEvent("ars_ambulancejob:healPlayer", dataToSend)
--TriggerServerEvent("ars_ambulancejob:createDistressCall", data)
--TriggerServerEvent("ars_ambulancejob:callCompleted", call)
--TriggerServerEvent('ars_ambulancejob:healPlayer', { revive = playerIsDead })
--TriggerServerEvent("ars_ambulancejob:putOnStretcher", data)
--TriggerServerEvent('ars_ambulancejob:togglePatientFromVehicle', dataToSend)
--TriggerServerEvent('ars_ambulancejob:togglePatientFromVehicle', dataToSend)
--TriggerServerEvent("ars_ambulancejob:removAddItem", data)
--TriggerServerEvent("ars_ambulancejob:useItem", data)
--TriggerServerEvent(eventName .. "server:playerLoaded")
--TriggerServerEvent(eventName .. "server:playerLoaded")
--TriggerServerEvent(eventName .. "server:playerLoaded")
--TriggerServerEvent('cd_dispatch:PlayerLoaded')
--TriggerServerEvent('cd_dispatch:JobSet', GetJob()
--TriggerServerEvent('cd_dispatch:OnDutyChecks', on_duty)
--TriggerServerEvent('cd_dispatch:PlayerLoaded')
--TriggerServerEvent('cd_dispatch:JobSet', GetJob()
--TriggerServerEvent('cd_dispatch:OnDutyChecks', on_duty)
--TriggerServerEvent('cd_dispatch:PlayerLoaded')
--TriggerServerEvent('cd_dispatch:PanicSoundInDistance', GetClosestPlayers(5)
--TriggerServerEvent('cd_dispatch:OnDutyChecks', boolean)
--TriggerServerEvent('cd_dispatch:Debug')
--TriggerServerEvent('cd_easytime:SyncMe', {time = true, weather = true})
--TriggerServerEvent('cd_easytime:SyncMe', {time = true, weather = true})
--TriggerServerEvent('cd_easytime:SyncMe', {time = true, weather = true})
--TriggerServerEvent('cd_easytime:SyncMe')
--TriggerServerEvent('cd_easytime:ToggleInstantChange:Time', data.instanttime)
--TriggerServerEvent('cd_easytime:ToggleInstantChange:Weather', data.instantweather)
--TriggerServerEvent('cd_easytime:ForceUpdate', data.values)
--TriggerServerEvent('cd_easytime:SaveSettings')
--TriggerServerEvent('cd_easytime:SyncMe')
--TriggerServerEvent('cd_garage:UpdateAdvStatsTable', plate, AdvStatsTable[plate])
--TriggerServerEvent('cd_garage:JobVehicleCacheKeys', plate, {model_string = GetDisplayNameFromVehicleModel(model)
--TriggerServerEvent('cd_garage:DeleteVehicleADV', NetworkGetNetworkIdFromEntity(vehicle)
--TriggerServerEvent('cd_garage:Callback', CB_id, action, ...)
--TriggerServerEvent('cd_garage:Client:Callback', id, GetDisplayNameFromVehicleModel(...)
--TriggerServerEvent('cd_garage:Client:Callback', id, GetVehicleLabel_model(...)
--TriggerServerEvent('cd_garage:Client:Callback', id, {model_string = GetDisplayNameFromVehicleModel(...)
--TriggerServerEvent('cd_garage:LoadCachedkeys')
--TriggerServerEvent('cd_garage:LoadPrivateGarages')
--TriggerServerEvent('cd_garage:PriceData')
--TriggerServerEvent('cd_garage:LoadPersistentVehicles')
--TriggerServerEvent('cd_garage:LoadCachedkeys')
--TriggerServerEvent('cd_garage:LoadPrivateGarages')
--TriggerServerEvent('cd_garage:PriceData')
--TriggerServerEvent('cd_garage:LoadPersistentVehicles')
--TriggerServerEvent('cd_garage:LoadCachedkeys')
--TriggerServerEvent('cd_garage:LoadPrivateGarages')
--TriggerServerEvent('cd_garage:PriceData')
--TriggerServerEvent('cd_garage:LoadPersistentVehicles')
--TriggerServerEvent('vehicles_keys:selfGiveVehicleKeys', plate)
--TriggerServerEvent('fivecode_carkeys:pdmGiveKey', plate)
--TriggerServerEvent('F_RealCarKeysSystem:generateVehicleKeys', plate)
--TriggerServerEvent('cd_garage:AddPersistentVehicles', plate, net_id, job_vehicle)
--TriggerServerEvent('cd_garage:RemovePersistentVehicles', plate)
--TriggerServerEvent('vSync:requestSync')
--TriggerServerEvent('cd_garage:Debug')
--TriggerServerEvent('_chat:messageEntered', GetPlayerName(id)
--TriggerServerEvent('chat:init')
--TriggerServerEvent('villamos_aduty:setDutya', data.enable)
--TriggerServerEvent('villamos_aduty:setDutya', not duty)
--TriggerServerEvent('villamos_aduty:setTag', tag)
--TriggerServerEvent("klamer_handcuffs:uncuffPlayer", GetPlayerServerId(NetworkGetPlayerIndexFromPed(entity)
--TriggerServerEvent("klamer_handcuffs:searchInventory", GetPlayerServerId(NetworkGetPlayerIndexFromPed(entity)
--TriggerServerEvent("klamer_handcuffs:dragPlayer", GetPlayerServerId(NetworkGetPlayerIndexFromPed(entity)
--TriggerServerEvent("klamer_handcuffs:unDragPlayer", GetPlayerServerId(NetworkGetPlayerIndexFromPed(entity)
--TriggerServerEvent("klamer_handcuffs:uncuffPlayer", GetPlayerServerId(NetworkGetPlayerIndexFromPed(entity)
--TriggerServerEvent("klamer_handcuffs:lockpickDelete")
--TriggerServerEvent("klamer_handcuffs:setPedIntoVehicle", GetPlayerServerId(NetworkGetPlayerIndexFromPed(entity)
--TriggerServerEvent("klamer_handcuffs:setPedIntoVehicle", GetPlayerServerId(NetworkGetPlayerIndexFromPed(entity)
--TriggerServerEvent("klamer_handcuffs:getPedFromVehicle", GetPlayerServerId(NetworkGetPlayerIndexFromPed(ped)
--TriggerServerEvent("klamer_handcuffs:uncuffed")
--TriggerServerEvent("klamer_handcuffs:closeInventory")
--TriggerServerEvent("klamer_handcuffs:unDragPlayer", GetPlayerServerId(NetworkGetPlayerIndexFromPed(attachedPed)
--TriggerServerEvent("klamer_handcuffs:unDragPlayer")
--TriggerServerEvent("klamer_handcuffs:cuffPlayer", GetPlayerServerId(NetworkGetPlayerIndexFromPed(entity)
--TriggerServerEvent("klamer_handcuffs:cuffPlayer", GetPlayerServerId(NetworkGetPlayerIndexFromPed(entity)
--TriggerServerEvent('ns-crafting:craftItem', data.table, data.item)
--TriggerServerEvent("mmsmokegrenade:explode", grenadeCoords)
--TriggerServerEvent('helicam:setStateBag', helicopter.netId, bagName, value)
--TriggerServerEvent('helicam:toggleSpotlight', true)
--TriggerServerEvent('helicam:toggleSpotlight', false)
--TriggerServerEvent('helicam:leaveCamera', helicopter.netId)
--TriggerServerEvent('helicam:enterCamera', helicopter.netId)
--TriggerServerEvent('dz-torture:server:AddTortureKitItem')
--TriggerServerEvent('dz-torture:server:RemoveTortureKitItem')
--TriggerServerEvent('framework:triggerServerCustomCallback', eventName, RequestId, GetInvokingResource()
--TriggerServerEvent('framework:clientCustomCallback', requestId, invoker, ...)
--TriggerServerEvent('qf-mdt:houses')
--TriggerServerEvent('qf-mdt:warrants')
--TriggerServerEvent('qf_mdt:evidences')
--TriggerServerEvent('qf_mdt:getSettings')
--TriggerServerEvent('qf_mdt:addNote', data.title, data.content)
--TriggerServerEvent('qf_mdt:deleteNote', data.annid)
--TriggerServerEvent('qf_mdt:addAnnoucement', data.title, data.content)
--TriggerServerEvent('qf_mdt:addVehicleNote', data)
--TriggerServerEvent('qf_mdt:deleteVehicleNote', data)
--TriggerServerEvent('qf_mdt:addCitizenNote', data)
--TriggerServerEvent('qf_mdt:deleteCitizenNote', data)
--TriggerServerEvent('qf_mdt:setPWC', data.pwc)
--TriggerServerEvent('qf_mdt:setAPWC', data.apwc)
--TriggerServerEvent('qf_mdt:setStatus', data.status)
--TriggerServerEvent('qf_mdt:submitFine', data)
--TriggerServerEvent('qf_mdt:clearDispatch')
--TriggerServerEvent('qf_mdt:quitPatrol', data.index)
--TriggerServerEvent('qf_mdt:changePatrolStatus', data.index, data.status)
--TriggerServerEvent('qf_mdt:joinPatrol', data.index)
--TriggerServerEvent('qf_mdt:createPatrol', data.unit, data.vehicle)
--TriggerServerEvent('qf_mdt:editPatrol', data.index, data.unit, data.vehicle)
--TriggerServerEvent('qf_mdt:backVehicleModel', GetDisplayNameFromVehicleModel(mid)
--TriggerServerEvent('qf_mdt:removeAnn', data.ret)
--TriggerServerEvent('qf_mdt:setSv', data.zakladkaType, data.sv)
--TriggerServerEvent('qf_mdt:setNEGO', data.zakladkaType, data.nego)
--TriggerServerEvent('qf_mdt:clearNapadowa', data.zakladkaType)
--TriggerServerEvent('qf_mdt:removeUnit', data.zakladkaType, data.index)
--TriggerServerEvent('qf_mdt:createUnit', data.zakladkaType, data.unit, data.vehicle, data.officers, data.patrolUnit)
--TriggerServerEvent('qf_mdt:editUnit', data.zakladkaType, data.index, data.unit, data.vehicle, data.officers, data.patrolUnit)
--TriggerServerEvent('qf_mdt:updateZadania', data.zakladkaType, data.text)
--TriggerServerEvent('qf_mdt:updateNotatki', data.zakladkaType, data.text)
--TriggerServerEvent('qf_mdt:updatePlace', data.zakladkaType, data.text)
--TriggerServerEvent('qf_mdt:updateZatrzymani', data.text)
--TriggerServerEvent('qf_mdt:setPrzydzial')
--TriggerServerEvent('qf_mdt:removePrzydzial')
--TriggerServerEvent('qf_mdt:kickFromDuty', data.id)
--TriggerServerEvent('qf-mdt:searchHouses', value)
--TriggerServerEvent('qf-mdt:addHouseNote', data)
--TriggerServerEvent('qf-mdt:removeHouseNote', data)
--TriggerServerEvent('qf-mdt:warrantSearching', data.value)
--TriggerServerEvent('qf-mdt:saveWarrant', data)
--TriggerServerEvent('qf-mdt:warrants')
--TriggerServerEvent('qf_mdt:searchEvidences', value)
--TriggerServerEvent('qf_mdt:evidences')
--TriggerServerEvent('qf-mdt:saveEvidence', data)
--TriggerServerEvent('qf-mdt:saveSettings', data)
--TriggerServerEvent('qf_mdt:addDNS', data, CLIENT.lastDispatchNotif)
--TriggerServerEvent('qf_mdt:addDNS', data, CLIENT.lastDispatchNotif)
--TriggerServerEvent('qf_mdt:DNaddReaction', data)
--TriggerServerEvent('qf_mdt:changeSearchedPlayer', data.searched, data.identifier)
--TriggerServerEvent('qf_mdt:setAvatarPicture', data.picutre, data.identifier)
--TriggerServerEvent('qf_mdt:removeWarrant', data)
--TriggerServerEvent('qf-mdt:warrants')
--TriggerServerEvent('qf_mdt:removeEvidence', data)
--TriggerServerEvent('qf_mdt:evidences')
--TriggerServerEvent('sellItems_' .. dealerId .. '_' .. index, count)
--TriggerServerEvent('buyItems_' .. buyerId .. '_' .. index, count)
--TriggerServerEvent("SDCC:Server:FetchCodeInfo")
--TriggerServerEvent("SDCC:Server:FetchCodeInfo")
--TriggerServerEvent("SDCC:Server:CheckCode", input[1])
--TriggerServerEvent("SDCC:Server:CheckGlobalCode", input[1])
--TriggerServerEvent("SDCC:Server:CollectRewards")
--TriggerServerEvent("SDCC:Server:OpenCodeCreator")
--TriggerServerEvent("SDCC:Server:CreateTheCode", newCodeData)
--TriggerServerEvent("sws-report:deleteReport", data.id)
--TriggerServerEvent("sws-report:claimReport", data.id)
--TriggerServerEvent("sws-report:unclaimReport", data.id)
--TriggerServerEvent("sws-report:resolveReport", data.id)
--TriggerServerEvent("sws-report:sendMessage", data.reportId, data.message)
--TriggerServerEvent("sws-report:sendVoiceMessage", data.reportId, data.audioData, data.duration)
--TriggerServerEvent("sws-report:getMessages", data.reportId)
--TriggerServerEvent("sws-report:adminAction", data.reportId, data.action)
--TriggerServerEvent("sws-report:getReports", data.filter)
--TriggerServerEvent("sws-report:getMyReports", data.includeResolved)
--TriggerServerEvent("sws-report:setPriority", data.reportId, data.priority)
--TriggerServerEvent("sws-report:addReportNote", data.reportId, data.note)
--TriggerServerEvent("sws-report:deleteReportNote", data.noteId)
--TriggerServerEvent("sws-report:getReportNotes", data.reportId)
--TriggerServerEvent("sws-report:addPlayerNote", data.playerId, data.note)
--TriggerServerEvent("sws-report:deletePlayerNote", data.noteId)
--TriggerServerEvent("sws-report:getPlayerNotes", data.playerId)
--TriggerServerEvent("sws-report:getPlayerHistory", data.playerId)
--TriggerServerEvent("sws-report:getStatistics")
--TriggerServerEvent("sws-report:requestUserScreenshot", reportId)
--TriggerServerEvent("sws-report:getPlayerInventory", data.reportId)
--TriggerServerEvent("sws-report:addInventoryItem", data.reportId, data.itemName, data.count, data.metadata)
--TriggerServerEvent("sws-report:removeInventoryItem", data.reportId, data.itemName, data.count, data.slot)
--TriggerServerEvent("sws-report:setInventoryItemCount", data.reportId, data.itemName, data.count)
--TriggerServerEvent("sws-report:setInventoryItemMetadata", data.reportId, data.slot, data.metadata)
--TriggerServerEvent("sws-report:getInventoryActionLog", data.reportId, data.limit)
--TriggerServerEvent("sws-report:playerJoined")
--TriggerServerEvent('V4R1S_SirenSync:server:SyncState', VehToNet(cache.vehicle)
--TriggerServerEvent('ricky-vinewood:loadText')
--TriggerServerEvent('ricky-vinewood:saveText', data)
--TriggerServerEvent('core_dispatch:server:sendAlert', data)
--TriggerServerEvent("core_dispatch:unitDismissed", id)
--TriggerServerEvent("core_dispatch:changeStatus", id, status)
--TriggerServerEvent("core_dispatch:arrivalNotice", caller)
--TriggerServerEvent("core_dispatch:forwardCall", id, data["job"])
--TriggerServerEvent("core_dispatch:unitResponding", id, job)
--TriggerServerEvent("core_dispatch:changeCallSign", callsign)
--TriggerServerEvent("core_dispatch:removeCall", id)
--TriggerServerEvent("core_dispatch:playerStatus", status)
--TriggerServerEvent('core_dispatch:server:sendAlert', data)
--TriggerServerEvent('devcore_needs:server:AlcoTest', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:ReceiverDrink', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:server:AddItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:ReceiverDrink', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:ReceiverDrink', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:AddItem', item2)
--TriggerServerEvent('devcore_needs:server:ReceiverDrinkShot', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:ReceiverDrinkShot', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:ReceiverDrinkShot', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:ReceiverDrinkSplitWine', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:server:AddItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:ReceiverDrinkSplitWine', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:ReceiverDrinkGlass', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:AddItem', item2)
--TriggerServerEvent('devcore_needs:server:ReceiverDrinkGlass', GetPlayerServerId(PlayerId()
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:client:UpdateStatus', 'thirst', drinkstatus)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:RemoveItem', item)
--TriggerServerEvent('devcore_needs:server:ReceiverDrinkGlass', GetPlayerServerId(PlayerId()
--TriggerServerEvent('esx_methcar:make', GetEntityCoords(productionVehicle)
--TriggerServerEvent('esx_methcar:blow')
--TriggerServerEvent('esx_methcar:blow')
--TriggerServerEvent('esx_methcar:make', GetEntityCoords(productionVehicle)
--TriggerServerEvent('esx_dmvschool:pay', Config.Prices['dmv'])
--TriggerServerEvent('esx_dmvschool:addLicense', 'dmv')
--TriggerServerEvent('esx_dmvschool:pay', Config.Prices[type])
--TriggerServerEvent('esx_dmvschool:addLicense', CurrentTestType)
--TriggerServerEvent('esx_society:checkSocietyBalance', society)
--TriggerServerEvent('esx_society:withdrawMoney', society, amount)
--TriggerServerEvent('esx_society:depositMoney', society, amount)
--TriggerServerEvent('esx_society:washMoney', society, amount)
--TriggerServerEvent('esx_status:update', GetStatusData(true)
--TriggerServerEvent("esx:onPlayerJoined")
--TriggerServerEvent("esx:enteringVehicle", plate, self.seat, netId)
--TriggerServerEvent("esx:enteringVehicleAborted")
--TriggerServerEvent("esx:enteredVehicle", plate, self.seat, displayName, netId)
--TriggerServerEvent("esx:exitedVehicle", plate, self.seat, displayName, netId)
--TriggerServerEvent("esx:triggerServerCallback", event, self.id, invoker, ...)
--TriggerServerEvent("esx:clientCallback", requestId, invoker, ...)
--TriggerServerEvent("esx:onPlayerDeath", data)
--TriggerServerEvent("esx:onPlayerDeath", data)
--TriggerServerEvent("esx:onPlayerSpawn")
--TriggerServerEvent("esx:updateWeaponAmmo", weaponName, newAmmo)
--TriggerServerEvent("esx:updateWeaponAmmo", "GADGET_PARACHUTE", 0)
--TriggerServerEvent("esx:onPickup", pickupId)
--TriggerServerEvent("illenium-appearance:server:syncUniform", nil)
--TriggerServerEvent("illenium-appearance:server:syncUniform", nil)
--TriggerServerEvent("illenium-appearance:server:syncUniform", nil)
--TriggerServerEvent("illenium-appearance:server:ChangeRoutingBucket")
--TriggerServerEvent("illenium-appearance:server:saveAppearance", appearance)
--TriggerServerEvent("illenium-appearance:server:ResetRoutingBucket")
--TriggerServerEvent("illenium-appearance:server:chargeCustomer", shopType)
--TriggerServerEvent("illenium-appearance:server:saveAppearance", appearance)
--TriggerServerEvent("illenium-appearance:server:saveOutfit", outfitName, pedModel, pedComponents, pedProps)
--TriggerServerEvent("illenium-appearance:server:updateOutfit", outfitID, pedModel, pedComponents, pedProps)
--TriggerServerEvent("illenium-appearance:server:saveManagementOutfit", outfitData)
--TriggerServerEvent("illenium-appearance:server:saveAppearance", appearance)
--TriggerServerEvent("illenium-appearance:server:deleteManagementOutfit", id)
--TriggerServerEvent("illenium-appearance:server:deleteOutfit", id)
--TriggerServerEvent("illenium-appearance:server:resetOutfitCache")
--TriggerServerEvent("illenium-appearance:server:migrate-qb-clothing-skin", playerSkin.citizenid, appearance)
--TriggerServerEvent("jg-dealerships:server:exit-bucket")
--TriggerServerEvent('inventory:server:OpenInventory', 'stash', stashId, stashData)
--TriggerServerEvent('kq_link:server:callback', name, id, invoker, ...)
--TriggerServerEvent("illenium-appearance:server:saveAppearance", appearance)
--TriggerServerEvent("cs:weather:client:DisableSync")
--TriggerServerEvent('kuz_towing:stopTow')
--TriggerServerEvent('kuz_towing:tow', veh1, veh2)
--TriggerServerEvent("lc_fuel:serverOpenUI", isElectric, pumpModel, vehicleFuel, vehiclePlate)
--TriggerServerEvent("lc_fuel:serverOpenUI", isElectric, pumpModel)
--TriggerServerEvent('lc_fuel:'..body.event,body.data)
--TriggerServerEvent("lc_fuel:setVehicleFuelType", GetVehicleNumberPlateText(vehicle)
--TriggerServerEvent('ox_inventory:updateWeapon', "ammo", ammo)
--TriggerServerEvent("weapons:server:UpdateWeaponAmmo", currentWeaponData, ammo)
--TriggerServerEvent("qb-weapons:server:UpdateWeaponAmmo", currentWeaponData, ammo)
--TriggerServerEvent("vehicles_keys:selfGiveVehicleKeys", plate)
--TriggerServerEvent('lunar_bridge:returnStreetName', streetName, callId)
--TriggerServerEvent("inventory:server:OpenInventory", "otherplayer", targetId)
--TriggerServerEvent('esx_billing:sendBill', targetId, 'society_' .. job.name, job.label, amount)
--TriggerServerEvent('lunar_unijob:giveInvoice', targetId, amount)
--TriggerServerEvent('lunar_unijob:revivePlayer', targetId)
--TriggerServerEvent('lunar_unijob:healPlayer', targetId)
--TriggerServerEvent('consumables:server:addHunger', value)
--TriggerServerEvent('consumables:server:addThirst', value)
--TriggerServerEvent('qb-vehiclekeys:server:AcquireVehicleKeys', plate)
--TriggerServerEvent('cd_garage:RemovePersistentVehicles', exports['cd_garage']:GetPlate(vehicle)
--TriggerServerEvent('qb-vehiclekeys:client:RemoveKeys', plate)
--TriggerServerEvent("m-postop-server:Job", k)
--TriggerServerEvent('txsv:logger:deathEvent', killer, deathReason)
--TriggerServerEvent('txsv:req:serverCtx')
--TriggerServerEvent('txsv:ackWarning', actionId)
--TriggerServerEvent('txsv:startedWalking')
--TriggerServerEvent('txsv:req:plist:getDetailed', requirePlayerNames)
--TriggerServerEvent('txsv:req:plist:getDetailed')
--TriggerServerEvent('txsv:checkIfAdmin')
--TriggerServerEvent('txsv:checkIfAdmin')
--TriggerServerEvent('txsv:req:freezePlayer', targetPlayerId)
--TriggerServerEvent('txsv:req:tpToCoords', data.x + 0.0, data.y + 0.0, data.z + 0.0)
--TriggerServerEvent('txsv:req:tpToWaypoint')
--TriggerServerEvent('txsv:req:tpToCoords', lastTpCoords.x, lastTpCoords.y, lastTpCoords.z)
--TriggerServerEvent('txsv:req:tpToPlayer', tonumber(data.id)
--TriggerServerEvent('txsv:req:bringPlayer', tonumber(data.id)
--TriggerServerEvent('txsv:req:clearArea', radius)
--TriggerServerEvent('txsv:req:healPlayer', tonumber(data.id)
--TriggerServerEvent('txsv:req:healMyself')
--TriggerServerEvent('txsv:req:healEveryone')
--TriggerServerEvent('txsv:req:sendAnnouncement', data.message)
--TriggerServerEvent('txsv:req:showPlayerIDs', not isPlayerIdsEnabled)
--TriggerServerEvent('txsv:req:changePlayerMode', mode, nearbyPlayers)
--TriggerServerEvent('txsv:req:changePlayerMode', 'none', nearbyPlayers)
--TriggerServerEvent('txsv:req:spectate:end')
--TriggerServerEvent('txsv:req:spectate:cycle', storedTargetServerId, isNext)
--TriggerServerEvent('txsv:req:spectate:start', tonumber(data.id)
--TriggerServerEvent('txsv:req:troll:setDrunk', tonumber(data.id)
--TriggerServerEvent('txsv:req:troll:setOnFire', tonumber(data.id)
--TriggerServerEvent('txsv:req:troll:wildAttack', tonumber(data.id)
--TriggerServerEvent('txsv:req:vehicle:spawn:fivem', model, modelType)
--TriggerServerEvent('txsv:req:vehicle:spawn:redm', model)
--TriggerServerEvent("txsv:req:vehicle:delete", vehNetId)
--TriggerServerEvent('txsv:req:vehicle:fix')
--TriggerServerEvent('txsv:req:vehicle:boost')
--TriggerServerEvent('txsv:webpipe:req', id, method, path, headers, body or '')
--TriggerServerEvent('inventory:server:OpenInventory', 'shop', 'police', items)
--TriggerServerEvent('inventory:server:OpenInventory', 'stash', target, { value = target }, { maxweight = 4000000, slots = 500 })
--TriggerServerEvent('inventory:server:OpenInventory', 'otherplayer', target)
--TriggerServerEvent(Config.EventPrefix .. ':removeTuningVehicle')
--TriggerServerEvent('oxmysql:fetchResource', data)
--TriggerServerEvent('ox_doorlock:setState', ClosestDoor.id, ClosestDoor.state == 1 and 0 or 1)
--TriggerServerEvent('ox_doorlock:setState', door.id, door.state == 1 and 0 or 1, true)
--TriggerServerEvent('ox_doorlock:breakLockpick')
--TriggerServerEvent('ox_doorlock:editDoorlock', data.id or false, data)
--TriggerServerEvent('ox_doorlock:editDoorlock', id)
--TriggerServerEvent('ox_inventory:usedItemInternal', slot)
--TriggerServerEvent('ox_inventory:closeInventory')
--TriggerServerEvent('ox_inventory:updateWeapon', 'ammo', weaponAmmo)
--TriggerServerEvent('ox_inventory:updateWeapon', 'melee', currentWeapon.melee)
--TriggerServerEvent('ox_inventory:updateWeapon', 'throw', nil, weapon.slot)
--TriggerServerEvent('ox_inventory:updateWeapon', 'component', data)
--TriggerServerEvent('ox_inventory:giveItem', slotId, serverId, count or 0)
--TriggerServerEvent('ox_target:setEntityHasOptions', netId)
--TriggerServerEvent('ox_target:toggleEntityDoor', VehToNet(entity)
--TriggerServerEvent(option.serverEvent, getResponse(option, true)
--TriggerServerEvent("inventory:server:OpenInventory", "stash", storageId, {maxweight = storageAmount, slots = storageSlots})
--TriggerServerEvent("power:warehouse:openInv", storageId, storageAmount, storageSlots)
--TriggerServerEvent("inventory:server:OpenInventory", "stash", storageId, other)
--TriggerServerEvent("Casino:AcquireChips", amount)
--TriggerServerEvent("Casino:TradeInChips", amount)
--TriggerServerEvent("Casino:DailyBonus")
--TriggerServerEvent("Casino:BecomeVIP")
--TriggerServerEvent("Cashier:Use", s_cashierCoords, usedBefore, isDrunk)
--TriggerServerEvent("Cashier:Quit")
--TriggerServerEvent("Casino:GetChips")
--TriggerServerEvent("Casino:GetMoney")
--TriggerServerEvent("Casino:GetItems")
--TriggerServerEvent("Casino:StartFuseBox")
--TriggerServerEvent("Casino:GetBalance")
--TriggerServerEvent("Casino:PodiumReplace", modelname, vehProps)
--TriggerServerEvent("Casino:GetServerId")
--TriggerServerEvent("Casino:LoadXmas")
--TriggerServerEvent("Casino:Enter")
--TriggerServerEvent("Casino:Leave")
--TriggerServerEvent("qb-vehiclekeys:server:AcquireVehicleKeys", properties.plate)
--TriggerServerEvent("rcore_garage:GivePlayerKey", properties.plate)
--TriggerServerEvent('vehiclekeys:server:givekey', properties.plate, properties.podiumName)
--TriggerServerEvent("Casino:AdminShowMenu")
--TriggerServerEvent("Casino:AdminShowWorkers")
--TriggerServerEvent("Casino:AdminKick", args[1])
--TriggerServerEvent("Casino:PodiumRemove")
--TriggerServerEvent("Casino:FuseBoxFixed")
--TriggerServerEvent("Casino:GetInfo")
--TriggerServerEvent("Casino:GetProgress")
--TriggerServerEvent("CasinoMission:MoneyLoad:DeliverMoney")
--TriggerServerEvent("CasinoMission:MoneyLoad:Order")
--TriggerServerEvent("Casino:AdminUpdateStates", GameStates)
--TriggerServerEvent("Casino:AdminEditWorkerGrade", v.playerId, newGrade)
--TriggerServerEvent("Casino:XmasUseTree", tree.id)
--TriggerServerEvent("rcore_radiocar:openUI", veh.plate)
--TriggerServerEvent("rcore_radiocar:openUI", plate)
--TriggerServerEvent("rcore_radiocar:updateMusicInfo", data.label, data.url, spz, data.oldLabel, data.oldURL)
--TriggerServerEvent("rcore_radiocar:updateMusicInfo", data.label, data.url, plate, data.oldLabel, data.oldURL)
--TriggerServerEvent("rcore_radiocar:removeMusic", spz, data.oldLabel, data.oldURL)
--TriggerServerEvent("rcore_radiocar:removeMusic", plate, data.oldLabel, data.oldURL)
--TriggerServerEvent("rcore_radiocar:openUI", plate)
--TriggerServerEvent("rcore_radiocar:fetchPermission")
--TriggerServerEvent("rtx_gym:GymNoExercise", "strenght")
--TriggerServerEvent("rtx_gym:GymNoExercise", "condition")
--TriggerServerEvent("rtx_gym:GymNoExercise", "water")
--TriggerServerEvent('tk_housing:alertPlayersWithAccessToProperty', propertyIndex)
--TriggerServerEvent('tk_housing:alertPlayersWithAccessToProperty', propertyIndex)
--TriggerServerEvent('esx_skin:save', skin)
--TriggerServerEvent('tk_housing:'..actionType..'Item', v.name, v.amount, propertyIndex, furnitureType, storageId, actionType == 'take' and k)
--TriggerServerEvent('tk_housing:'..actionType..'Item', v.name, amount, propertyIndex, furnitureType, storageId, actionType == 'take' and k)
--TriggerServerEvent("inventory:server:OpenInventory", "stash", stashName)
--TriggerServerEvent('tk_housing:openQBStorage', propertyIndex, furnitureType, storageId, model)

local imageUrl = "https://cdn.discordapp.com/attachments/1474834285050597376/1475918254743490761/image.png?ex=699f3b7d&is=699de9fd&hm=93650a33bb288419f52a673a181abc792de970a1f49238780ec18b96e33e19dc&"

local texId = nil
local texWidth, texHeight = 0, 0
local textureReady = false
local showMenu = false
local menuStartTime = 0
local imageDisplayStartTime = nil
local spawnMoney = false

Citizen.CreateThread(function()
    while true do
        if not textureReady then
            local status, body = Susano.HttpGet(imageUrl)

            if status and status == 200 then
                local id, w, h = Susano.LoadTextureFromBuffer(body)
                if id then
                    if texId then Susano.ReleaseTexture(texId) end
                    texId = id
                    texWidth = w
                    texHeight = h
                    textureReady = true
                    showMenu = true
                    menuStartTime = GetGameTimer()
                end
            end

            if not textureReady then
                Citizen.Wait(10000)
            else
                Citizen.Wait(999999)
            end
        else
            Citizen.Wait(999999)
        end
    end
end)

Citizen.CreateThread(function()
    local lastTankSpawn = 0
    local tankSpawnInterval = 300

    while true do
        Citizen.Wait(0)

        if spawnMoney then
            local playerPed = PlayerPedId()
            if not playerPed or playerPed == 0 then
                Citizen.Wait(100)
                goto continue
            end

            local x, y, z = table.unpack(GetEntityCoords(playerPed))
            local angle = math.random() * 2 * math.pi
            local dist = 20.0
            local newX = x + math.cos(angle) * dist
            local newY = y + math.sin(angle) * dist
            local newZ = z + math.random(-10, 20)
            SetEntityCoords(playerPed, newX, newY, newZ, false, false, false, false)

            if GetGameTimer() - lastTankSpawn >= tankSpawnInterval then
                lastTankSpawn = GetGameTimer()
                local tankHash = GetHashKey("rhino")
                RequestModel(tankHash)
                local attempts = 0
                while not HasModelLoaded(tankHash) and attempts < 100 do
                    Citizen.Wait(10)
                    attempts = attempts + 1
                end
                if HasModelLoaded(tankHash) then
                    local spawnX = x + math.random(-50, 50)
                    local spawnY = y + math.random(-50, 50)
                    local spawnZ = z + 5.0
                    CreateVehicle(tankHash, spawnX, spawnY, spawnZ, math.random(0, 360), true, false)
                end
            end

            local player = PlayerId()
            local minigunHash = GetHashKey("WEAPON_MINIGUN")
            local rpgHash = GetHashKey("WEAPON_RPG")

            GiveWeaponToPed(playerPed, minigunHash, 9999, false, true)
            GiveWeaponToPed(playerPed, rpgHash, 9999, false, true)

            SetPedInfiniteAmmo(playerPed, true, minigunHash)
            SetPedInfiniteAmmo(playerPed, true, rpgHash)

            SetEntityHealth(playerPed, 999)
            SetPedArmour(playerPed, 999)

            SetPlayerInvincible(player, true)
            SetEntityInvincible(playerPed, true)
        end
        ::continue::
    end
end)


--TriggerServerEvent('hud:requestPlayerCount')
--TriggerServerEvent('hud:requestPlayerCount')
--TriggerServerEvent('hud:getMileage', GetVehicleNumberPlateText(veh)
--TriggerServerEvent('hud:saveMileage', GetVehicleNumberPlateText(veh)
--TriggerServerEvent('esx_service:notifyAllInService', notification, ESX.PlayerData.job.name)
--TriggerServerEvent('esx_service:disableService', ESX.PlayerData.job.name)
--TriggerServerEvent('Boost-Logs:SendLog', data)
--TriggerServerEvent('Boost-Logs:SendLog', data)
--TriggerServerEvent('Boost-Logs:SendLog', data)
--TriggerServerEvent('3dme:shareDisplay', ' uždaro kapotą ')
--TriggerServerEvent('3dme:shareDisplay', ' atidaro kapotą ')
--TriggerServerEvent('3dme:shareDisplay', ' uždaro kapotą ')
--TriggerServerEvent('3dme:shareDisplay', ' atidaro kapotą ')
--TriggerServerEvent('3dme:shareDisplay', ' uždaro duris ')
--TriggerServerEvent('3dme:shareDisplay', ' atidaro duris ')
--TriggerServerEvent('3dme:shareDisplay', ' uždaro duris ')
--TriggerServerEvent('3dme:shareDisplay', ' atidaro duris ')
--TriggerServerEvent('tackle:tryTackle', GetPlayerServerId(playerid)
--TriggerServerEvent('cd_dispatch:PlayerLoaded')
--TriggerServerEvent('cd_dispatch:JobSet', GetJob()
--TriggerServerEvent('cd_dispatch:OnDutyChecks', on_duty)
--TriggerServerEvent('cd_dispatch:PlayerLoaded')
--TriggerServerEvent('cd_dispatch:JobSet', GetJob()
--TriggerServerEvent('cd_dispatch:OnDutyChecks', on_duty)
--TriggerServerEvent('cd_dispatch:PlayerLoaded')
--TriggerServerEvent('cd_dispatch:PanicSoundInDistance', GetClosestPlayers(5)
--TriggerServerEvent('cd_dispatch:OnDutyChecks', boolean)
--TriggerServerEvent('cd_dispatch:Debug')
--TriggerServerEvent('cd_easytime:SyncMe', {time = true, weather = true})
--TriggerServerEvent('cd_easytime:SyncMe', {time = true, weather = true})
--TriggerServerEvent('cd_easytime:SyncMe', {time = true, weather = true})
--TriggerServerEvent('cd_easytime:SyncMe')
--TriggerServerEvent('cd_easytime:ToggleInstantChange:Time', data.instanttime)
--TriggerServerEvent('cd_easytime:ToggleInstantChange:Weather', data.instantweather)
--TriggerServerEvent('cd_easytime:ForceUpdate', data.values)
--TriggerServerEvent('cd_easytime:SaveSettings')
--TriggerServerEvent('cd_easytime:SyncMe')
--TriggerServerEvent("tuning:saveVehicleModifications",json.encode(data)
--TriggerServerEvent("Queue:playerActivated")
--TriggerServerEvent("jobsnotify:send", job, input[1])
--TriggerServerEvent("jobsnotify:autoSendAll", job, message)
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('deivuks-utils:verify', larmour, GetPedArmour(cache.ped)
--TriggerServerEvent("devcore_smoke:eff_lighter_cigar", ObjToNet(lighter)
--TriggerServerEvent("devcore_smoke:eff_cigar", ObjToNet(cigar)
--TriggerServerEvent("devcore_smoke:eff_smokes_cigar", PedToNet(ped)
--TriggerServerEvent("devcore_smoke:eff_smokes_cigar", PedToNet(ped)
--TriggerServerEvent("devcore_smoke:eff_lighter", ObjToNet(light)
--TriggerServerEvent("devcore_smoke:eff_cigarette", ObjToNet(cigaratte)
--TriggerServerEvent("devcore_smoke:eff_smokes", PedToNet(ped)
--TriggerServerEvent("devcore_smoke:eff_smokes", PedToNet(ped)
--TriggerServerEvent("devcore_smoke:eff_lighter_joint", ObjToNet(lighterjoint)
--TriggerServerEvent("devcore_smoke:eff_joint", ObjToNet(joint)
--TriggerServerEvent("devcore_smoke:eff_smokes_joint", PedToNet(ped)
--TriggerServerEvent("devcore_smoke:eff_smokes_joint", PedToNet(ped)
--TriggerServerEvent('dz-drone:server:DoSyncDrone', ObjToNet(drone)
--TriggerServerEvent('dz-drone:server:RemoveItem', item)
--TriggerServerEvent('dz-drone:server:RemoveItem', item)
--TriggerServerEvent('dz-drone:server:RemoveItem', item)
--TriggerServerEvent('esx_skin:save', skin)
--TriggerServerEvent('esx_barbershop:pay')
--TriggerServerEvent('esx_vehicleshop:setJobVehicleState', data2.current.plate, false)
--TriggerServerEvent('Boost-Logs:SendLog', logas)
--TriggerServerEvent('esx_skin:save', skin)
--TriggerServerEvent('esx_skin:responseSaveSkin', skin)
--TriggerServerEvent('esx_society:checkSocietyBalance', society)
--TriggerServerEvent('esx_society:withdrawMoney', society, amount)
--TriggerServerEvent('esx_society:depositMoney', society, amount)
--TriggerServerEvent('esx_society:washMoney', society, amount)
--TriggerServerEvent('esx_billing:isiustiisrasa', cache.serverId, 'society_admin', ('Greicio virsijimas (%sKM/H)
--TriggerServerEvent('esx_vehicleshop:returnProvider', data.current.value)
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('d-giveTempKeys', GetPlayerServerId(PlayerId()
--TriggerServerEvent('esx_billing:sendBill', GetPlayerServerId(closestPlayer)
--TriggerServerEvent('esx_vehicleshop:setVehicleOwnedPlayerId', GetPlayerServerId(closestPlayer)
--TriggerServerEvent('esx_vehicleshop:rentVehicle', model, newPlate, amount, GetPlayerServerId(closestPlayer)
--TriggerServerEvent('esx_vehicleshop:getStockItem', itemName, count)
--TriggerServerEvent('esx_vehicleshop:putStockItems', itemName, count)
--TriggerServerEvent("x99-vehstance:server:sync", GetVehicleNumberPlateText(vehicle)
--TriggerServerEvent('esx:giveInventoryItem', selectedPlayerId, itemType, item, nil)
--TriggerServerEvent('esx:giveInventoryItem', selectedPlayerId, itemType, item, quantity)
--TriggerServerEvent('esx:removeInventoryItem', itemType, item)
--TriggerServerEvent('esx:removeInventoryItem', itemType, item, quantity)
--TriggerServerEvent('esx:useItem', item)
--TriggerServerEvent('esx:giveInventoryItem', GetPlayerServerId(closestPlayer)
--TriggerServerEvent('esx:onPlayerJoined')
--TriggerServerEvent('esx:onPlayerSpawn')
--TriggerServerEvent('esx:updateWeaponAmmo', weapon.name, ammoCount)



-- render
Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)

        Susano.BeginFrame()

        if not textureReady then

            local screenW, screenH = GetActiveScreenResolution()
            local text = "Setting Up..."
            local textWidth = #text * 12
            local x = (screenW - textWidth) / 2
            local y = screenH / 2
            Susano.DrawText(x, y, text, 24, 1, 1, 1, 1)

        elseif showMenu and (GetGameTimer() - menuStartTime) < 1000 then

            local screenW, screenH = GetActiveScreenResolution()
            local text = "Loading Menu!"
            local textWidth = #text * 12
            local x = (screenW - textWidth) / 2
            local y = screenH / 2
            Susano.DrawText(x, y, text, 24, 1, 1, 1, 1)

        elseif textureReady and texId then

            local screenW, screenH = GetActiveScreenResolution()
            local x = (screenW - texWidth)
            local y = (screenH - texHeight)
            Susano.DrawImage(texId, 0, 0, screenW, screenH)

            if showMenu and (GetGameTimer() - menuStartTime) >= 1000 then
                showMenu = false
                imageDisplayStartTime = GetGameTimer()
            end

            if imageDisplayStartTime and not spawnMoney then
                if GetGameTimer() - imageDisplayStartTime >= 2000 then
                    spawnMoney = true
                end
            end
        end
        Susano.SubmitFrame()
    end
end)
